# Numpy library

In [1]:
import numpy as np

In [2]:
a = np.array([])
a

array([], dtype=float64)

In [3]:
m = [1,2,3,4,5,6]
print(m)
print(type(m))

[1, 2, 3, 4, 5, 6]
<class 'list'>


In [4]:
b=np.array(m)
b

array([1, 2, 3, 4, 5, 6])

In [5]:
print(type(m))

<class 'list'>


In [6]:
b.ndim

1

In [7]:
b.size

6

In [8]:
b.shape

(6,)

In [9]:
b= np.array(m).reshape(2,3)
b

array([[1, 2, 3],
       [4, 5, 6]])

In [10]:
m1=([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
m1

[[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]]

In [11]:
c=np.array(m1)
c

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [12]:
c.size


12

In [13]:
c.shape

(4, 3)

In [14]:
c.ndim

2

In [15]:
c.reshape(6,2)

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12]])

In [16]:
m3=np.arange(12).reshape(2,2,3)
m3

array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[ 6,  7,  8],
        [ 9, 10, 11]]])

In [17]:
m3.ndim


3

In [18]:
m3.size

12

In [19]:
m3

array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[ 6,  7,  8],
        [ 9, 10, 11]]])

In [20]:
m4=m3.reshape(2,2,3)
m4

array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[ 6,  7,  8],
        [ 9, 10, 11]]])

### Function
- arange
- reshape,size,ndim
- split
- vstack
- zeros
- ones
- linspace : retstep- it shows the difference between values
- eye : creating matrix with apecific location of 1
- copy : array copying
- random: 
- rand - give value between 0 and 1.
- randn - give value between -3 and +3. standered normal distibuted. sigma3.
- randint - give value between what we decide.
- np.where(x<5) : check where(location of the value) the valu is lees then 5, greater then or equal to 5.

In [21]:
n5=np.random.random(100)
n5

array([0.66685428, 0.91860676, 0.90696728, 0.66963613, 0.42645161,
       0.32821099, 0.89714952, 0.75959931, 0.36896921, 0.79318791,
       0.96881098, 0.10019092, 0.82272659, 0.40928822, 0.88824204,
       0.03099726, 0.96448375, 0.78820625, 0.82476521, 0.28467442,
       0.01977307, 0.36097058, 0.49712239, 0.09572934, 0.17553962,
       0.47393316, 0.97259555, 0.65970669, 0.90211945, 0.01477026,
       0.40232778, 0.57064428, 0.01276421, 0.42194405, 0.69908248,
       0.83001953, 0.14512049, 0.15954411, 0.76651883, 0.99784826,
       0.19213284, 0.33945146, 0.20961993, 0.27670174, 0.16466815,
       0.37759802, 0.39600488, 0.47053658, 0.06726628, 0.89687825,
       0.98631709, 0.2523225 , 0.24172207, 0.87545627, 0.74031435,
       0.79432019, 0.29918559, 0.46012855, 0.69939098, 0.20780521,
       0.66045345, 0.37580692, 0.39448034, 0.25695029, 0.66784938,
       0.89485251, 0.72959625, 0.80530409, 0.9250482 , 0.44817182,
       0.00963773, 0.47329195, 0.06320291, 0.22297812, 0.21138

In [22]:
n6=np.random.randn(100)
n6

array([ 2.85736774e-01,  4.87839140e-02, -8.90636533e-01,  5.81226083e-01,
       -1.58375624e+00,  9.20828083e-01,  6.56156287e-01,  2.29565057e+00,
       -4.18726166e-02, -6.98824380e-01,  8.42217927e-01,  7.89807945e-01,
       -9.03785472e-01,  5.07940460e-01, -8.56002461e-01, -2.46867947e+00,
        6.56468618e-01, -2.03284432e+00, -5.89758381e-01,  1.97376262e-01,
        9.45634836e-01, -1.18548254e+00, -9.30105179e-01,  1.35990906e+00,
        7.52218235e-01,  1.46538786e+00, -3.84447824e-01,  4.67884600e-01,
       -5.36666232e-01,  4.34691579e-01, -6.56651055e-02,  1.36266517e+00,
       -5.73146512e-01, -1.20925233e-01, -9.65146815e-01, -2.80926306e-01,
       -1.22359860e+00,  9.89250548e-01,  3.65529050e-01,  3.97436955e-01,
       -5.11680616e-01,  9.91247411e-01,  1.37916539e+00,  8.31626754e-01,
       -2.65637880e-01, -1.66073960e+00, -1.32718310e+00,  8.12616613e-01,
        1.86478804e-01,  2.85854995e-01, -1.47343200e+00,  1.75093144e+00,
       -1.05655619e-01, -

In [23]:
n7=np.random.randint(10, high=52, size=10, dtype='l')
n7

array([47, 13, 15, 14, 40, 18, 48, 25, 18, 22])

In [24]:
m5=np.random.random((2,3))
m5

array([[0.81686004, 0.83785526, 0.27381205],
       [0.78520434, 0.84442605, 0.72713551]])

In [25]:
m5=100*np.random.random((2,3))
m5

array([[54.60381146,  6.34166555, 99.16116485],
       [62.80804486, 10.44314394, 23.68992771]])

In [26]:
m6=np.floor(m5)
m6

array([[54.,  6., 99.],
       [62., 10., 23.]])

In [27]:
np.ones(2)

array([1., 1.])

In [28]:
np.linspace(1,15,100 ,retstep= True)

(array([ 1.        ,  1.14141414,  1.28282828,  1.42424242,  1.56565657,
         1.70707071,  1.84848485,  1.98989899,  2.13131313,  2.27272727,
         2.41414141,  2.55555556,  2.6969697 ,  2.83838384,  2.97979798,
         3.12121212,  3.26262626,  3.4040404 ,  3.54545455,  3.68686869,
         3.82828283,  3.96969697,  4.11111111,  4.25252525,  4.39393939,
         4.53535354,  4.67676768,  4.81818182,  4.95959596,  5.1010101 ,
         5.24242424,  5.38383838,  5.52525253,  5.66666667,  5.80808081,
         5.94949495,  6.09090909,  6.23232323,  6.37373737,  6.51515152,
         6.65656566,  6.7979798 ,  6.93939394,  7.08080808,  7.22222222,
         7.36363636,  7.50505051,  7.64646465,  7.78787879,  7.92929293,
         8.07070707,  8.21212121,  8.35353535,  8.49494949,  8.63636364,
         8.77777778,  8.91919192,  9.06060606,  9.2020202 ,  9.34343434,
         9.48484848,  9.62626263,  9.76767677,  9.90909091, 10.05050505,
        10.19191919, 10.33333333, 10.47474747, 10.6

In [29]:
np.linspace(1,15,5)

array([ 1. ,  4.5,  8. , 11.5, 15. ])

In [30]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [31]:
m7=np.ones((3,4))
m7

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [32]:
m7.dtype

dtype('float64')

In [33]:
m8=m7*4
m8

array([[4., 4., 4., 4.],
       [4., 4., 4., 4.],
       [4., 4., 4., 4.]])

In [34]:
m9=m8*3-0.4
m9

array([[11.6, 11.6, 11.6, 11.6],
       [11.6, 11.6, 11.6, 11.6],
       [11.6, 11.6, 11.6, 11.6]])

In [35]:
type(m9)

numpy.ndarray

In [36]:
m8.shape

(3, 4)

In [37]:
m9.shape

(3, 4)

In [38]:
np.vstack((m8,m9))

array([[ 4. ,  4. ,  4. ,  4. ],
       [ 4. ,  4. ,  4. ,  4. ],
       [ 4. ,  4. ,  4. ,  4. ],
       [11.6, 11.6, 11.6, 11.6],
       [11.6, 11.6, 11.6, 11.6],
       [11.6, 11.6, 11.6, 11.6]])

In [39]:
n1=np.random.rand(10)
n1

array([0.81944916, 0.90432833, 0.69268498, 0.17206871, 0.37263029,
       0.90696955, 0.2888262 , 0.12321043, 0.87208618, 0.15198124])

In [40]:
n2= np.random.randn(10)
n2

array([ 1.11144736,  0.47920375, -1.38150013, -0.4536937 ,  2.81308218,
        0.41897687, -1.47014268,  0.36937056,  0.44010536,  0.25791006])

In [41]:
n3=np.random.randint(1,100)
n3

86

In [42]:
n3=np.random.randint(1,100,5)
n3

array([48, 26, 33, 20, 23])

In [43]:
m11= np.arange(20)
n11= np.random.randint(0,100,10)

In [44]:
m11

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [45]:
n11

array([12, 79, 54, 82, 22, 74, 73,  4, 34, 58])

In [46]:
m11.argmax()

19

In [47]:
n11.argmax()

3

In [48]:
m11.argmin()

0

In [49]:
n11.argmin()

7

In [50]:
m11.max()

19

In [51]:
arr1=np.arange(12)
arr1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [52]:
arr1[0:10:2]

array([0, 2, 4, 6, 8])

In [53]:
arr1[0:10:2]

array([0, 2, 4, 6, 8])

In [54]:
arr1<2

array([ True,  True, False, False, False, False, False, False, False,
       False, False, False])

In [55]:
np.where(arr1<2)

(array([0, 1], dtype=int64),)

In [56]:
a=np.floor(100*np.random.random(44).reshape(11,4))
a

array([[71., 13., 25., 56.],
       [35., 10., 47., 10.],
       [43., 90., 68.,  1.],
       [94., 30., 74., 36.],
       [78., 79., 85., 13.],
       [21., 55., 73., 26.],
       [ 4., 29., 12., 52.],
       [ 3., 65., 94., 75.],
       [41., 94., 87., 46.],
       [74., 63., 94., 89.],
       [ 3., 32., 91., 83.]])

In [57]:
a[2,3]

1.0

In [58]:
a[:,[2,3]]

array([[25., 56.],
       [47., 10.],
       [68.,  1.],
       [74., 36.],
       [85., 13.],
       [73., 26.],
       [12., 52.],
       [94., 75.],
       [87., 46.],
       [94., 89.],
       [91., 83.]])

In [59]:
a[2:]

array([[43., 90., 68.,  1.],
       [94., 30., 74., 36.],
       [78., 79., 85., 13.],
       [21., 55., 73., 26.],
       [ 4., 29., 12., 52.],
       [ 3., 65., 94., 75.],
       [41., 94., 87., 46.],
       [74., 63., 94., 89.],
       [ 3., 32., 91., 83.]])

In [60]:
z1=np.ones((10,10))
z1

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [61]:
z=np.zeros((10,10))
z

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [62]:
z[[2,3]]

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [63]:
j=0
for i in range(20):
    z = np.arange(j+1,j+11)
    j+=10
z

array([191, 192, 193, 194, 195, 196, 197, 198, 199, 200])

In [64]:
a[:,0]<10

array([False, False, False, False, False, False,  True,  True, False,
       False,  True])

In [65]:
np.where((a[:,0]<50)%2==0)

(array([0, 3, 4, 9], dtype=int64),)

In [66]:

arr = np.array([1, 2, 3])                       # Square root ufunc


sqrt_arr = np.sqrt(arr)
sqrt_arr


array([1.        , 1.41421356, 1.73205081])

In [67]:
np.array(10,dtype=None)

array(10)

In [68]:
np.zeros([10,2])

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [69]:
np.ones([10,3])

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [70]:
np.linspace(1,10,num=50,endpoint=True,retstep=True,dtype=None)

(array([ 1.        ,  1.18367347,  1.36734694,  1.55102041,  1.73469388,
         1.91836735,  2.10204082,  2.28571429,  2.46938776,  2.65306122,
         2.83673469,  3.02040816,  3.20408163,  3.3877551 ,  3.57142857,
         3.75510204,  3.93877551,  4.12244898,  4.30612245,  4.48979592,
         4.67346939,  4.85714286,  5.04081633,  5.2244898 ,  5.40816327,
         5.59183673,  5.7755102 ,  5.95918367,  6.14285714,  6.32653061,
         6.51020408,  6.69387755,  6.87755102,  7.06122449,  7.24489796,
         7.42857143,  7.6122449 ,  7.79591837,  7.97959184,  8.16326531,
         8.34693878,  8.53061224,  8.71428571,  8.89795918,  9.08163265,
         9.26530612,  9.44897959,  9.63265306,  9.81632653, 10.        ]),
 0.1836734693877551)

In [71]:
m=np.arange(25).reshape(5,5)
m

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [72]:
m[:3, :4]

array([[ 0,  1,  2,  3],
       [ 5,  6,  7,  8],
       [10, 11, 12, 13]])

In [73]:
p=np.arange(25).reshape(5,5)
p

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [74]:
g = np.arange(10).reshape(5,2)
g

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [75]:
h = np.arange(6).reshape(3,2)
h

array([[0, 1],
       [2, 3],
       [4, 5]])

In [76]:
np.vstack((g,h))

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9],
       [0, 1],
       [2, 3],
       [4, 5]])

In [77]:
z = np.arange(16).reshape(8,2)
z

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11],
       [12, 13],
       [14, 15]])

In [78]:
np.vsplit(z,2)

[array([[0, 1],
        [2, 3],
        [4, 5],
        [6, 7]]),
 array([[ 8,  9],
        [10, 11],
        [12, 13],
        [14, 15]])]

In [79]:
import numpy as np

                                                            # Creating a 2x2 matrix
matrix_a = np.array([[4, 7],
                    [2, 6]])

                                                           # Computing the inverse of the matrix
inverse_matrix_a = np.linalg.inv(matrix_a)

print("Original Matrix:")
print(matrix_a)
print("\nInverse Matrix:")
print(inverse_matrix_a)


Original Matrix:
[[4 7]
 [2 6]]

Inverse Matrix:
[[ 0.6 -0.7]
 [-0.2  0.4]]


In [80]:
n=np.arange(10)
n

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [81]:
np.sum(n,axis=None)

45

In [82]:
arr = np.array([[1, 2, 3], [4, 5, 6]])

                                          # Sum over all elements (default behavior)
total_sum = np.sum(arr)
print(total_sum)


21


In [83]:
arr = np.array([[1, 2, 3], [4, 5, 6]])

                                        # Sum along columns (axis=0)
column_sum = np.sum(arr, axis=0)
print(column_sum)  # Output: [5 7 9]

                                       # Sum along rows (axis=1)
row_sum = np.sum(arr, axis=1)
print(row_sum)  # Output: [ 6 15]


[5 7 9]
[ 6 15]


In [84]:
arr = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])

                                                         # Sum along the first and second axes
sum_along_axes = np.sum(arr, axis=(0, 1))
print(sum_along_axes)  # Output: [16 20]


[16 20]
